import demoT from '../assets/demoShirt.png';
import demoD from '../assets/demoDress.png';
import demoS from '../assets/demoShoes.png';
import demoA from '../assets/demoAcc.png';

export const products = [
  { id: '1d', name: 'Dress 1', image: demoD, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '2d', name: 'Dress 2', image: demoD, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '3d', name: 'Dress 3', image: demoD, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '4d', name: 'Dress 4', image: demoD, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '5d', name: 'Dress 5', image: demoD, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '6d', name: 'Dress 6', image: demoD, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '7d', name: 'Dress 7', image: demoD, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '8d', name: 'Dress 8', image: demoD, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Dress',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // Add more products as needed

  { id: '1t', name: 'Shirt 1', image: demoT, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Shirt',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '2t', name: 'Shirt 2', image: demoT, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Shirt',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '3t', name: 'Shirt 3', image: demoT, imageB: demoS, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Shirt' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  { id: '4t', name: 'Shirt 4', image: demoT, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Shirt' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  // { id: '5t', name: 'Shirt 5', image: demoT, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Shirt',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '6t', name: 'Shirt 6', image: demoT, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Shirt',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '7t', name: 'Shirt 7', image: demoT, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Shirt',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '8t', name: 'Shirt 8', image: demoT, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Shirt' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  // Add more products as needed

  { id: '1s', name: 'Shoe 1', image: demoS, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Shoes' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  { id: '2s', name: 'Shoe 2', image: demoS, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '3s', name: 'Shoe 3', image: demoS, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Shoes' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  { id: '4s', name: 'Shoe 4', image: demoS, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '5s', name: 'Shoe 5', image: demoS, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '6s', name: 'Shoe 6', image: demoS, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '7s', name: 'Shoe 7', image: demoS, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // { id: '8s', name: 'Shoe 8', image: demoS, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Shoes',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // Add more products as needed

  { id: '1a', name: 'Jewelry 1', image: demoA, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  { id: '2a', name: 'Jewelry 2', image: demoA, originalPrice: 179.99, rating: 4.0, reviews: 8, category: 'Jewelry' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'},
  { id: '3a', name: 'Jewelry 3', image: demoA, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8,reviews: 15, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'  },
  { id: '4a', name: 'jwelery 4', image: demoS, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'  },
   // { id: '5', name: 'jwelery 5', image: demo, originalPrice: 159.99, offerPrice: 129.99, rating: 4.5, reviews: 10, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'  },
  // { id: '6', name: 'jwelery 6', image: demo, originalPrice: 179.99,  rating: 4.0, reviews: 8, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'  },
  // { id: '7', name: 'jwelery 7', image: demo, originalPrice: 199.99, rating: 4.8, reviews: 15, category: 'Jewelry',description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.'  },
  // { id: '8', name: 'jwelery 8', image: demo, originalPrice: 199.99, offerPrice: 149.99, rating: 4.8, reviews: 15, category: 'Jewelry' ,description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum consequatur repellendus consequuntur quisquam rem corrupti quo facilis ea, quaerat eum facere illum, fugit magnam iure rerum quae autem, vitae totam doloribus iste. Quam, impedit voluptatum culpa debitis necessitatibus a delectus numquam, fuga explicabo quis laudantium omnis eligendi excepturi tempore, adipisci ea sequi! Recusandae temporibus sunt odio quis dolor cumque.' },
  // Add more products as needed
];
